mysql:
  db: ""
  host: ""
  password: ""
  port: ""
  user: ""

redis:
  host: ""
  port: ""
  db: 0
  password: ""


secret: SbitdyN5ZH39cNxSrG3kMNZ1GfiyyQ43

auth:
  use_deeptrain: false

server:
  port: 8094
system:
  general:
    backend: ""
  phone:
    accesskey: ""
    signature: ""
    template: "pub_verif_basic"
  mail:
    host: ""
    port: 465
    username: ""
    password: ""
    from: ""
  search:
    endpoint: https://duckduckgo-api.vercel.app
    query: 5
