mysql:
  db: chatnio
  host: 192.168.53.6
  password: Nucleus!
  port: 31412
  user: rdapp

redis:
  host: 192.168.53.6
  port: 30579
  db: 0
  password: "Nucleus!"


secret: SbitdyN5ZH39cNxSrG3kMNZ1GfiyyQ43

auth:
  use_deeptrain: false

server:
  port: 8094
system:
  general:
    backend: ""
  mail:
    host: ""
    port: 465
    username: ""
    password: ""
    from: ""
  search:
    endpoint: https://duckduckgo-api.vercel.app
    query: 5
